### ISSUE TITLE
最新版弹幕过滤报错，不加没事

### ISSUE THREAD

**Issue by Ms213s** [SmallPeaches/DanmakuRender#106]
[2023-09-05 22:15:36,485][main][DEBUG]: DEBUG VERSION: 4-2023.9.1
[2023-09-05 22:15:36,486][main][DEBUG]: args: Namespace(config='replay.yml', default_config='configs/default.yml', debug=False, version=False, skip_update=False)
[2023-09-05 22:15:36,486][main][DEBUG]: Full config: {
    "测试": {
        "output_dir": "./测试",
        "output_name": "测试丨{YEAR}-{MONTH}-{DAY} {HOUR}_{MINUTE}",
        "engine": "ffmpeg",
        "segment": 3000,
        "danmaku": true,
        "video": true,
        "auto_render": true,
        "end_cnt": 10,
        "resolution": [
            1920,
            1080
        ],
        "vid_format": "flv",
        "flow_cdn": "tx",
        "ffmpeg_stream_args": [
            "-fflags",
            "+discardcorrupt",
            "-reconnect",
            "1",
            "-rw_timeout",
            "10000000",
            "-analyzeduration",
            "15000000",
            "-probesize",
            "50000000",
            "-thread_queue_size",
            "16"
        ],
        "disable_lowspeed_interrupt": false,
        "check_stream_changes": false,
        "dm_format": "ass",
        "margin_h": 6,
        "margin_w": 0.05,
        "dmrate": 0.1,
        "font": "Microsoft YaHei",
        "fontsize": 36,
        "dst": 20,
        "dmduration": 16,
        "opacity": 0.4,
        "auto_fontsize": true,
        "outlinecolor": 0,
        "outlinesize": 1.0,
        "dm_delay_fixed": 3.0,
        "dm_auto_restart": 300,
        "dm_filter": [
            "菜",
            "fw"
        ],
        "url": "https://www.huya.com/kaerlol",
        "render": {
            "output_dir": null,
            "format": "flv",
            "engine": "ffmpeg",
            "nrenders": 1,
            "hwaccel_args": [
                "-hwaccel",
                "auto"
            ],
            "vencoder": "h264_nvenc",
            "vencoder_args": [
                "-b:v",
                "4M"
            ],
            "aencoder": "aac",
            "aencoder_args": [
                "-b:a",
                "128K"
            ],
            "output_resize": null,
            "nproc": 2,
            "bufsize": 100,
            "danmaku_resort": false
        },
        "clean": {
            "method": null,
            "dest": null,
            "delay": 172800
        }
    }
}
[2023-09-05 22:15:36,487][__init__][INFO]: 添加直播：https://www.huya.com/kaerlol
[2023-09-05 22:15:36,496][connectionpool][DEBUG]: Starting new HTTPS connection (1): www.huya.com:443
[2023-09-05 22:15:36,855][connectionpool][DEBUG]: https://www.huya.com:443 "GET /kaerlol HTTP/1.1" 200 13066
[2023-09-05 22:15:36,861][connectionpool][DEBUG]: Starting new HTTPS connection (1): mp.huya.com:443
[2023-09-05 22:15:36,962][connectionpool][DEBUG]: https://mp.huya.com:443 "GET /cache.php?m=Live&do=profileRoom&roomid=521000 HTTP/1.1" 200 None
[2023-09-05 22:15:36,965][connectionpool][DEBUG]: Starting new HTTPS connection (1): mp.huya.com:443
[2023-09-05 22:15:37,090][connectionpool][DEBUG]: https://mp.huya.com:443 "GET /cache.php?m=Live&do=profileRoom&roomid=521000 HTTP/1.1" 200 None
[2023-09-05 22:15:37,091][__init__][DEBUG]: PIPE MESSAGE: {'src': 'downloader', 'msg': 'start', 'type': 'info', 'group': '测试'}
[2023-09-05 22:15:37,092][__init__][INFO]: 测试 录制开始.
[2023-09-05 22:15:37,093][connectionpool][DEBUG]: Starting new HTTPS connection (1): mp.huya.com:443
[2023-09-05 22:15:37,205][connectionpool][DEBUG]: https://mp.huya.com:443 "GET /cache.php?m=Live&do=profileRoom&roomid=521000 HTTP/1.1" 200 None
[2023-09-05 22:15:37,208][connectionpool][DEBUG]: Starting new HTTPS connection (1): mp.huya.com:443
[2023-09-05 22:15:37,316][connectionpool][DEBUG]: https://mp.huya.com:443 "GET /cache.php?m=Live&do=profileRoom&roomid=521000 HTTP/1.1" 200 None
[2023-09-05 22:15:37,319][connectionpool][DEBUG]: Starting new HTTP connection (1): 127.0.0.1:7890
[2023-09-05 22:15:37,474][connectionpool][DEBUG]: http://127.0.0.1:7890 "GET http://tx.flv.huya.com/src/367138632-367138632-1576848417538179072-734400720-10057-A-0-1-imgplus.flv?wsSecret=1c07713344c2779c4cff239dc2ae535b&wsTime=64f88988&ctype=tars_mp&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_%2A-265_%2A&exsphd=264_500%2C264_2000%2C264_4000%2C264_10000%2C&t=102&ver=1&sv=2110211124&seqid=1693923337000 HTTP/1.1" 200 None
[2023-09-05 22:15:37,649][ffmpegio][DEBUG]: FFmpegDownloader args:
[2023-09-05 22:15:37,649][ffmpegio][DEBUG]: ['tools/ffmpeg.exe', '-y', '-headers', 'Content-Type: application/x-www-form-urlencoded\r\nUser-Agent: Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Mobile Safari/537.36 \r\n', '-fflags', '+discardcorrupt', '-reconnect', '1', '-rw_timeout', '10000000', '-analyzeduration', '15000000', '-probesize', '50000000', '-thread_queue_size', '16', '-i', 'http://tx.flv.huya.com/src/367138632-367138632-1576848417538179072-734400720-10057-A-0-1-imgplus.flv?wsSecret=1c07713344c2779c4cff239dc2ae535b&wsTime=64f88988&ctype=tars_mp&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_%2A-265_%2A&exsphd=264_500%2C264_2000%2C264_4000%2C264_10000%2C&t=102&ver=1&sv=2110211124&seqid=1693923337000', '-c', 'copy', '-f', 'segment', '-segment_time', '3000', '-reset_timestamps', '1', '-movflags', 'faststart+frag_keyframe+empty_moov', './测试\\测试-20230905-221537-Part%03d.flv']
[2023-09-05 22:15:37,651][connectionpool][DEBUG]: Starting new HTTPS connection (1): mp.huya.com:443
[2023-09-05 22:15:38,343][connectionpool][DEBUG]: https://mp.huya.com:443 "GET /cache.php?m=Live&do=profileRoom&roomid=521000 HTTP/1.1" 200 None
[2023-09-05 22:15:38,345][__init__][ERROR]: 'DanmakuWriter' object has no attribute 'dm_filter'
Traceback (most recent call last):
  File "E:\新建文件夹\DMR\Downloader\__init__.py", line 182, in start_helper
    self.start_once()
  File "E:\新建文件夹\DMR\Downloader\__init__.py", line 149, in start_once
    return future.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\新建文件夹\DMR\Downloader\__init__.py", line 116, in danmaku_thread
    self.dmw = DanmakuWriter(self.url,
  File "E:\新建文件夹\DMR\Downloader\danmakuio.py", line 37, in __init__
    self.dm_filter = [re.compile(str(x)) for x in self.dm_filter]
AttributeError: 'DanmakuWriter' object has no attribute 'dm_filter'
[2023-09-05 22:15:38,346][__init__][ERROR]: 'NoneType' object has no attribute 'stop'
Traceback (most recent call last):
  File "E:\新建文件夹\DMR\Downloader\__init__.py", line 182, in start_helper
    self.start_once()
  File "E:\新建文件夹\DMR\Downloader\__init__.py", line 149, in start_once
    return future.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\新建文件夹\DMR\Downloader\__init__.py", line 116, in danmaku_thread
    self.dmw = DanmakuWriter(self.url,
  File "E:\新建文件夹\DMR\Downloader\danmakuio.py", line 37, in __init__
    self.dm_filter = [re.compile(str(x)) for x in self.dm_filter]
AttributeError: 'DanmakuWriter' object has no attribute 'dm_filter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\新建文件夹\DMR\Downloader\__init__.py", line 214, in stop_once
    self.dmw.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
[2023-09-05 22:15:38,347][ffmpegio][DEBUG]: 测试 ffmpeg: ffmpeg version 6.0-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
Input #0, flv, from 'http://tx.flv.huya.com/src/367138632-367138632-1576848417538179072-734400720-10057-A-0-1-imgplus.flv?wsSecret=1c07713344c2779c4cff239dc2ae535b&wsTime=64f88988&ctype=tars_mp&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_%2A-265_%2A&exsphd=264_500%2C264_2000%2C264_4000%2C264_10000%2C&t=102&ver=1&sv=2110211124&seqid=1693923337000':
Metadata:
codecname       : 0
server          : TLSS/2.0.0(qcloud)
server_version  : 2.0.0
Duration: N/A, start: 4347.999000, bitrate: N/A
Stream #0:0: Subtitle: text
Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp
Stream #0:2: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 62.50 fps, 60 tbr, 1k tbn
[segment @ 000001fe0db308c0] Opening './测试\测试-20230905-221537-Part000.flv' for writing
Output #0, segment, to './测试\测试-20230905-221537-Part%03d.flv':
Metadata:
codecname       : 0
server          : TLSS/2.0.0(qcloud)
server_version  : 2.0.0
encoder         : Lavf60.3.100
Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 62.50 fps, 60 tbr, 1k tbn
Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp
Stream mapping:
Stream #0:2 -> #0:0 (copy)
Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help

[2023-09-05 22:15:38,404][ffmpegio][DEBUG]: ffmpeg out: 

[q] command received. Exiting.

frame=  423 fps=0.0 q=-1.0 Lsize=N/A time=00:00:07.03 bitrate=N/A speed=11.3x    
video:3307kB audio:138kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
.
[2023-09-05 22:15:38,404][ffmpegio][DEBUG]: ffmpeg downloader stoped.
[2023-09-05 22:15:38,404][__init__][DEBUG]: PIPE MESSAGE: {'src': 'downloader', 'msg': 'restart', 'type': 'error', 'group': '测试', 'desc': AttributeError("'DanmakuWriter' object has no attribute 'dm_filter'")}
[2023-09-05 22:15:38,405][__init__][ERROR]: 录制 测试 遇到错误，即将重试.
[2023-09-05 22:15:38,405][__init__][ERROR]: 'DanmakuWriter' object has no attribute 'dm_filter'
[2023-09-05 22:15:38,405][connectionpool][DEBUG]: Starting new HTTPS connection (1): mp.huya.com:443
[2023-09-05 22:15:38,577][connectionpool][DEBUG]: https://mp.huya.com:443 "GET /cache.php?m=Live&do=profileRoom&roomid=521000 HTTP/1.1" 200 None
[2023-09-05 22:15:38,579][__init__][DEBUG]: PIPE MESSAGE: {'src': 'downloader', 'msg': 'start', 'type': 'info', 'group': '测试'}
[2023-09-05 22:15:38,580][__init__][INFO]: 测试 录制开始.
[2023-09-05 22:15:38,580][connectionpool][DEBUG]: Starting new HTTPS connection (1): mp.huya.com:443
[2023-09-05 22:15:38,775][connectionpool][DEBUG]: https://mp.huya.com:443 "GET /cache.php?m=Live&do=profileRoom&roomid=521000 HTTP/1.1" 200 None
[2023-09-05 22:15:38,778][connectionpool][DEBUG]: Starting new HTTPS connection (1): mp.huya.com:443
[2023-09-05 22:15:38,946][connectionpool][DEBUG]: https://mp.huya.com:443 "GET /cache.php?m=Live&do=profileRoom&roomid=521000 HTTP/1.1" 200 None
[2023-09-05 22:15:38,949][connectionpool][DEBUG]: Starting new HTTP connection (1): 127.0.0.1:7890
[2023-09-05 22:15:38,996][connectionpool][DEBUG]: http://127.0.0.1:7890 "GET http://tx.flv.huya.com/src/367138632-367138632-1576848417538179072-734400720-10057-A-0-1-imgplus.flv?wsSecret=08cf846c1aaea78cc0e1e46e16be660e&wsTime=64f8898a&ctype=tars_mp&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_%2A-265_%2A&exsphd=264_500%2C264_2000%2C264_4000%2C264_10000%2C&t=102&ver=1&sv=2110211124&seqid=1693923338000 HTTP/1.1" 200 None
[2023-09-05 22:15:39,155][ffmpegio][DEBUG]: FFmpegDownloader args:
[2023-09-05 22:15:39,156][ffmpegio][DEBUG]: ['tools/ffmpeg.exe', '-y', '-headers', 'Content-Type: application/x-www-form-urlencoded\r\nUser-Agent: Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Mobile Safari/537.36 \r\n', '-fflags', '+discardcorrupt', '-reconnect', '1', '-rw_timeout', '10000000', '-analyzeduration', '15000000', '-probesize', '50000000', '-thread_queue_size', '16', '-i', 'http://tx.flv.huya.com/src/367138632-367138632-1576848417538179072-734400720-10057-A-0-1-imgplus.flv?wsSecret=08cf846c1aaea78cc0e1e46e16be660e&wsTime=64f8898a&ctype=tars_mp&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_%2A-265_%2A&exsphd=264_500%2C264_2000%2C264_4000%2C264_10000%2C&t=102&ver=1&sv=2110211124&seqid=1693923338000', '-c', 'copy', '-f', 'segment', '-segment_time', '3000', '-reset_timestamps', '1', '-movflags', 'faststart+frag_keyframe+empty_moov', './测试\\测试-20230905-221539-Part%03d.flv']
[2023-09-05 22:15:39,157][connectionpool][DEBUG]: Starting new HTTPS connection (1): mp.huya.com:443
[2023-09-05 22:15:39,286][connectionpool][DEBUG]: https://mp.huya.com:443 "GET /cache.php?m=Live&do=profileRoom&roomid=521000 HTTP/1.1" 200 None
[2023-09-05 22:15:39,288][__init__][ERROR]: 'DanmakuWriter' object has no attribute 'dm_filter'
Traceback (most recent call last):
  File "E:\新建文件夹\DMR\Downloader\__init__.py", line 182, in start_helper
    self.start_once()
  File "E:\新建文件夹\DMR\Downloader\__init__.py", line 149, in start_once
    return future.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\新建文件夹\DMR\Downloader\__init__.py", line 116, in danmaku_thread
    self.dmw = DanmakuWriter(self.url,
  File "E:\新建文件夹\DMR\Downloader\danmakuio.py", line 37, in __init__
    self.dm_filter = [re.compile(str(x)) for x in self.dm_filter]
AttributeError: 'DanmakuWriter' object has no attribute 'dm_filter'
[2023-09-05 22:15:39,289][__init__][ERROR]: 'NoneType' object has no attribute 'stop'
Traceback (most recent call last):
  File "E:\新建文件夹\DMR\Downloader\__init__.py", line 182, in start_helper
    self.start_once()
  File "E:\新建文件夹\DMR\Downloader\__init__.py", line 149, in start_once
    return future.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\新建文件夹\DMR\Downloader\__init__.py", line 116, in danmaku_thread
    self.dmw = DanmakuWriter(self.url,
  File "E:\新建文件夹\DMR\Downloader\danmakuio.py", line 37, in __init__
    self.dm_filter = [re.compile(str(x)) for x in self.dm_filter]
AttributeError: 'DanmakuWriter' object has no attribute 'dm_filter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\新建文件夹\DMR\Downloader\__init__.py", line 214, in stop_once
    self.dmw.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
[2023-09-05 22:15:39,290][ffmpegio][DEBUG]: 测试 ffmpeg: ffmpeg version 6.0-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100

[2023-09-05 22:15:39,304][ffmpegio][DEBUG]: ffmpeg out:   Metadata:
    codecname       : 0
    server          : TLSS/2.0.0(qcloud)
    server_version  : 2.0.0
  Duration: N/A, start: 4347.999000, bitrate: N/A
  Stream #0:0: Subtitle: text
  Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp
  Stream #0:2: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 62.50 fps, 60 tbr, 1k tbn
[segment @ 000002e8c52f08c0] Opening './测试\测试-20230905-221539-Part000.flv' for writing
Output #0, segment, to './测试\测试-20230905-221539-Part%03d.flv':
  Metadata:
    codecname       : 0
    server          : TLSS/2.0.0(qcloud)
    server_version  : 2.0.0
    encoder         : Lavf60.3.100
  Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 62.50 fps, 60 tbr, 1k tbn
  Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp
Stream mapping:
  Stream #0:2 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help

[q] command received. Exiting.

frame=    0 fps=0.0 q=-1.0 Lsize=N/A time=-577014:32:22.77 bitrate=N/A speed=N/A    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
.
[2023-09-05 22:15:39,304][ffmpegio][DEBUG]: ffmpeg downloader stoped.
[2023-09-05 22:15:39,304][__init__][DEBUG]: PIPE MESSAGE: {'src': 'downloader', 'msg': 'restart', 'type': 'error', 'group': '测试', 'desc': AttributeError("'DanmakuWriter' object has no attribute 'dm_filter'")}
[2023-09-05 22:15:39,305][__init__][ERROR]: 录制 测试 遇到错误，即将重试.
[2023-09-05 22:15:39,305][__init__][ERROR]: 'DanmakuWriter' object has no attribute 'dm_filter'

**Comment by SmallPeaches** [comment]
已经推送更新
