### ISSUE TITLE
如何使用自动清理功能

### ISSUE THREAD

**Issue by zxcec** [SmallPeaches/DanmakuRender#117]
完全不知道怎么调，照猫画虎做的设置没用
clean:
  src_video:
    # 先复制到一个文件夹
    - method: move
      dest: /backup
      delay: 20
    - method: delete
      delay: 172800
  dm_video:
    # 先复制到一个文件夹
    - method: move
      dest: /acfun
      delay: 20

**Comment by SmallPeaches** [comment]
你把这段填到哪里了，应该是在replay-xxx.yml里面改。另外这个自动清理是需要上传完成才会进行的。

**Comment by zxcec** [comment]
[Desktop.zip](https://github.com/SmallPeaches/DanmakuRender/files/12775631/Desktop.zip)
设置完会报错，显示
`[2023-10-01 06:04:22,418][__init__][INFO]: 添加以下文件到清理队列： ['./直播回放（带弹幕版）\\咪诺今天也要元气满满-2023年10月01日05点59分22秒（带弹幕版）.mp4', './直播回放（带弹幕版）\\咪诺今天也要元气满满-2023年10月01日06点00分31秒（带弹幕版）.mp4', './直播回放（带弹幕版）\\咪诺今天也要元气满满-2023年10月01日06点01分33秒（带弹幕版）.mp4'].
[2023-10-01 06:04:22,420][__init__][DEBUG]: PIPE MESSAGE: {'src': 'uploader', 'msg': ('xxx', 'dm_video'), 'type': 'end', 'group': ('xxx', 'dm_video')}
[2023-10-01 06:04:42,435][__init__][DEBUG]: Clean files: {'msg_type': 'clean', 'method': 'move', 'video': './直播回放（带弹幕版）\\咪诺今天也要元气满满-2023年10月01日06点01分33秒（带弹幕版）.mp4', 'group': 'xxx', 'video_info': {'url': 'https://live.bilibili.com/22815234', 'taskname': 'xxx', 'streamer': '咪诺今天也要元气满满', 'title': '【学歌中】该陪小老婆了~', 'time': datetime.datetime(2023, 10, 1, 5, 59, 22, 677152), 'has_danmu': '（带弹幕版）', 'duration': 68.88649010658264}, 'config': {'dest': '/acfun', 'delay': 20, 'strict': True, 'wait': True, 'method': 'move'}, 'kwargs': {}}
[2023-10-01 06:04:42,435][__init__][ERROR]: 'str' object has no attribute 'startwith'
Traceback (most recent call last):
  File "D:\desktop\DanmakuRender-4\DMR\Cleaner\__init__.py", line 45, in _run_queue
    if dst and not dst.startwith('*'):
AttributeError: 'str' object has no attribute 'startwith'
[2023-10-01 06:04:42,438][__init__][DEBUG]: Clean files: {'msg_type': 'clean', 'method': 'move', 'video': './直播回放（带弹幕版）\\咪诺今天也要元气满满-2023年10月01日05点59分22秒（带弹幕版）.mp4', 'group': 'xxx', 'video_info': {'url': 'https://live.bilibili.com/22815234', 'taskname': 'xxx', 'streamer': '咪诺今天也要元气满满', 'title': '【学歌中】该陪小老婆了~', 'time': datetime.datetime(2023, 10, 1, 5, 59, 22, 677152), 'has_danmu': '（带弹幕版）', 'duration': 68.88649010658264}, 'config': {'dest': '/acfun', 'delay': 20, 'strict': True, 'wait': True, 'method': 'move'}, 'kwargs': {}}
[2023-10-01 06:04:42,438][__init__][DEBUG]: PIPE MESSAGE: {'src': 'cleaner', 'msg': 'D:\\desktop\\DanmakuRender-4\\直播回放（带弹幕版）\\咪诺今天也要元气满满-2023年10月01日06点01分33秒（带弹幕版）.mp4', 'type': 'error', 'group': None, 'desc': AttributeError("'str' object has no attribute 'startwith'")}
[2023-10-01 06:04:42,438][__init__][ERROR]: 'str' object has no attribute 'startwith'
Traceback (most recent call last):
  File "D:\desktop\DanmakuRender-4\DMR\Cleaner\__init__.py", line 45, in _run_queue
    if dst and not dst.startwith('*'):
AttributeError: 'str' object has no attribute 'startwith'
[2023-10-01 06:04:42,440][__init__][DEBUG]: Clean files: {'msg_type': 'clean', 'method': 'move', 'video': './直播回放（带弹幕版）\\咪诺今天也要元气满满-2023年10月01日06点00分31秒（带弹幕版）.mp4', 'group': 'xxx', 'video_info': {'url': 'https://live.bilibili.com/22815234', 'taskname': 'xxx', 'streamer': '咪诺今天也要元气满满', 'title': '【学歌中】该陪小老婆了~', 'time': datetime.datetime(2023, 10, 1, 5, 59, 22, 677152), 'has_danmu': '（带弹幕版）', 'duration': 68.88649010658264}, 'config': {'dest': '/acfun', 'delay': 20, 'strict': True, 'wait': True, 'method': 'move'}, 'kwargs': {}}
[2023-10-01 06:04:42,439][__init__][ERROR]: 文件 D:\desktop\DanmakuRender-4\直播回放（带弹幕版）\咪诺今天也要元气满满-2023年10月01日06点01分33秒（带弹幕版）.mp4 清理错误.
[2023-10-01 06:04:42,440][__init__][ERROR]: 'str' object has no attribute 'startwith'
Traceback (most recent call last):
  File "D:\desktop\DanmakuRender-4\DMR\Cleaner\__init__.py", line 45, in _run_queue
    if dst and not dst.startwith('*'):
AttributeError: 'str' object has no attribute 'startwith'
[2023-10-01 06:04:42,441][__init__][ERROR]: 'str' object has no attribute 'startwith'
[2023-10-01 06:04:42,441][__init__][DEBUG]: PIPE MESSAGE: {'src': 'cleaner', 'msg': 'D:\\desktop\\DanmakuRender-4\\直播回放（带弹幕版）\\咪诺今天也要元气满满-2023年10月01日05点59分22秒（带弹幕版）.mp4', 'type': 'error', 'group': None, 'desc': AttributeError("'str' object has no attribute 'startwith'")}
[2023-10-01 06:04:42,442][__init__][ERROR]: 文件 D:\desktop\DanmakuRender-4\直播回放（带弹幕版）\咪诺今天也要元气满满-2023年10月01日05点59分22秒（带弹幕版）.mp4 清理错误.
[2023-10-01 06:04:42,442][__init__][ERROR]: 'str' object has no attribute 'startwith'
[2023-10-01 06:04:42,443][__init__][DEBUG]: PIPE MESSAGE: {'src': 'cleaner', 'msg': 'D:\\desktop\\DanmakuRender-4\\直播回放（带弹幕版）\\咪诺今天也要元气满满-2023年10月01日06点00分31秒（带弹幕版）.mp4', 'type': 'error', 'group': None, 'desc': AttributeError("'str' object has no attribute 'startwith'")}
[2023-10-01 06:04:42,443][__init__][ERROR]: 文件 D:\desktop\DanmakuRender-4\直播回放（带弹幕版）\咪诺今天也要元气满满-2023年10月01日06点00分31秒（带弹幕版）.mp4 清理错误.
[2023-10-01 06:04:42,444][__init__][ERROR]: 'str' object has no attribute 'startwith'
`

**Comment by SmallPeaches** [comment]
应该是后面改其他功能的时候出的一个小bug，过两天我修复一下
