### ISSUE TITLE
直播结束正在等待

### ISSUE THREAD

**Issue by upane** [SmallPeaches/DanmakuRender#135]
用的docker环境和Linux环境出现 

即将添加以下配置文件：['configs/replay-yyf.yml']
[2023-10-13 11:24:02,712][INFO]: 添加直播：https://www.douyu.com/110
[2023-10-13 11:24:03,523][INFO]: yyf 直播结束，正在等待.

试了两台都这样

**Comment by MAE5blog** [comment]
怎么解决的

**Comment by upane** [comment]
> 怎么解决的

/app/DanmakuRender-4 # python3 /app/DanmakuRender-4/DMR/LiveAPI/douyu.py 

Traceback (most recent call last):
  File "/app/DanmakuRender-4/DMR/LiveAPI/douyu.py", line 253, in <module>
    print(api.get_stream_url())
  File "/app/DanmakuRender-4/DMR/LiveAPI/douyu.py", line 214, in get_stream_url
    js = execjs.compile(func_ub9)
  File "/usr/lib/python3.9/site-packages/execjs/__init__.py", line 61, in compile
    return get().compile(source, cwd)
  File "/usr/lib/python3.9/site-packages/execjs/_runtimes.py", line 21, in get
    return get_from_environment() or _find_available_runtime()
  File "/usr/lib/python3.9/site-packages/execjs/_runtimes.py", line 49, in _find_available_runtime
    raise exceptions.RuntimeUnavailableError("Could not find an available JavaScript runtime.")
execjs._exceptions.RuntimeUnavailableError: Could not find an available JavaScript runtime.

看日志是js执行失败了，
安装下node和npm 就ok
