### ISSUE TITLE
退出程序問題

### ISSUE THREAD

**Issue by alfredt999** [SmallPeaches/DanmakuRender#138]
要按兩次CTRL-C才能退出, 好像有報錯. 是正常的嗎?

^C^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1537, in _shutdown
    atexit_call()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt:

**Comment by SmallPeaches** [comment]
按一次正常情况下是会卡住的。因为要等待其他的进程退出（例如上传和下载进程），如果你再按一次就是强行退出，一般情况下两个没什么区别（最多是录制文件名称没改这种小问题），但是如果你使用mp4格式的话，不等其他进程结束可能会导致视频损坏。

**Comment by alfredt999** [comment]
只按一下的話它會一直卡住不結束.
![圖片](https://github.com/SmallPeaches/DanmakuRender/assets/142170821/b0db845f-e5f3-4b82-b7be-9fbafd05ec1e)
