### ISSUE TITLE
一直出现 直播流读取错误，然后重试

### ISSUE THREAD

**Issue by ysf142161354901** [SmallPeaches/DanmakuRender#140]
录一会就出现下面错误 然后重录
Traceback (most recent call last):
  File "C:\Users\14216\Videos\DanmakuRender-2023.10.2\DMR\Downloader\__init__.py", line 186, in start_helper
    self.start_once()
  File "C:\Users\14216\Videos\DanmakuRender-2023.10.2\DMR\Downloader\__init__.py", line 153, in start_once
    return future.result()
  File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 433, in result
    return self.__get_result()
  File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "C:\Program Files\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\14216\Videos\DanmakuRender-2023.10.2\DMR\Downloader\__init__.py", line 141, in video_thread
    self.downloader.start()
  File "C:\Users\14216\Videos\DanmakuRender-2023.10.2\DMR\Downloader\ffmpegio.py", line 235, in start
    return self.start_helper()
  File "C:\Users\14216\Videos\DanmakuRender-2023.10.2\DMR\Downloader\ffmpegio.py", line 217, in start_helper
    raise RuntimeError(f'{self.taskname} 直播流读取错误, 即将重试.')
[DMR-20231020-10.log](https://github.com/SmallPeaches/DanmakuRender/files/13050514/DMR-20231020-10.log)
[DMR-20231020-11.log](https://github.com/SmallPeaches/DanmakuRender/files/13050515/DMR-20231020-11.log)

**Comment by SmallPeaches** [comment]
看起来像是程序本身的问题，你要不试下重装一下环境和程序？

**Comment by ysf142161354901** [comment]
重装之后  大概用几次后就会又这样

**Comment by SmallPeaches** [comment]
找到问题了，是新版本FFmpeg输出和旧版不一样的原因，预计下个版本修复，现在可以先暂时自己下载一个旧版FFmpeg解决（https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-5.1.2-essentials_build.zip）。

**Comment by SmallPeaches** [comment]
找到问题了，是新版本FFmpeg输出和旧版不一样的原因，预计下个版本修复，现在可以先暂时自己下载一个旧版FFmpeg解决（https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-5.1.2-essentials_build.zip ）

**Comment by foeris** [comment]
> 找到问题了，是新版本FFmpeg输出和旧版本不一样的原因，前期下个版本修复，现在可以先暂时自己下载一个旧版本FFmpeg解决（[https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg -5.1.2-essentials_build.zip](https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-5.1.2-essentials_build.zip)）

使用此版本的FFmpeg之后还是会出问题，录制了89分钟后中断

[2023-10-24 15:29:09,687][ERROR]: FFmpeg 退出.
Traceback (most recent call last):
  File "D:\DanmakuRender-2023.10.2\DMR\Downloader\__init__.py", line 186, in start_helper
    self.start_once()
  File "D:\DanmakuRender-2023.10.2\DMR\Downloader\__init__.py", line 153, in start_once
    return future.result()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\DanmakuRender-2023.10.2\DMR\Downloader\__init__.py", line 141, in video_thread
    self.downloader.start()
  File "D:\DanmakuRender-2023.10.2\DMR\Downloader\ffmpegio.py", line 235, in start
    return self.start_helper()
  File "D:\DanmakuRender-2023.10.2\DMR\Downloader\ffmpegio.py", line 146, in start_helper
    raise RuntimeError(f'FFmpeg 退出.')
RuntimeError: FFmpeg 退出.

这个怎么搞呢

**Comment by SmallPeaches** [comment]
中断之后会不会自动重启继续录制呢？如果会的话就是正常的，有可能是网络原因直播波动了一下，然后导致录播错误重启了

**Comment by foeris** [comment]
> 中断之后会不会自动重启继续录制呢？如果会的话就是正常的，有可能是网络原因直播波动了一下，然后导致录播错误重启了

好的，会重启录制，不过没有反馈开始录制的信息
