### ISSUE TITLE
从旧版本升级以后，单独录制弹幕模式异常，无法正常分段且会报错

### ISSUE THREAD

**Issue by lizongcong** [SmallPeaches/DanmakuRender#145]
从旧版本（2023.9.23）升级到新版本（2023.10.2）以后，单独录制弹幕模式（即设置danmaku为True，video和auto_render为False）出现异常。弹幕内容可以正常录制，但无法分段且会报错。而在旧版本下，该模式正常运行。

我试过重启电脑和重新配置环境，但没有解决。希望大神们能帮忙看一下。

## 配置文件

```
# 本文件一个代表一个录制任务，这里的设置基本上包含了所有可用的参数
# 配置文件编写请参考 https://github.com/SmallPeaches/DanmakuRender 

# 直播间链接
url: https://live.douyin.com/267041505106

# 录制输出文件夹，设置为空则使用主播名称作为文件夹
output_dir: ./media

# 录制文件名称格式，可使用关键字替换，默认效果：飞天狙想要努力变胖-2023年3月1日20点30分，注意这里不能含有冒号，斜杠等非法字符！！
output_name: '{STREAMER}-{YEAR}年{MONTH}月{DAY}日{HOUR}点{MINUTE}分'

# 录制程序引擎，可选ffmpeg（由ffmpeg提供拉流服务）或者streamgears（使用streamgears提供拉流服务，此功能正在测试）
# 在使用streamgears作为录制引擎时，录制视频格式只能是flv
engine: ffmpeg

# 录播分段时间（秒），默认一个小时
segment: 120

# 是否录制弹幕
danmaku: True

# 是否录制直播流
video: False

# 启动自动渲染
auto_render: False
```

## 报错信息
```
PS D:\DanmakuRender-bak> python .\main.py
即将添加以下配置文件：['configs\\replay-测试.yml']
[2023-10-26 04:48:08,240][INFO]: 添加直播：https://live.douyin.com/267041505106
[2023-10-26 04:48:09,106][INFO]: 测试 录制开始.
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "D:\DanmakuRender-bak\DMR\Downloader\danmakuio.py", line 68, in monitor
    self.split()
TypeError: split() missing 1 required positional argument: 'part_start_time'
[2023-10-26 04:48:10,279][INFO]: Websocket connected
```

**Comment by lizongcong** [comment]
谢谢大神修复
