### ISSUE TITLE
开启边录边传，有一定概率弹幕文件提示文件被占用导致无法转换名称

### ISSUE THREAD

**Issue by chenfanz** [SmallPeaches/DanmakuRender#166]
开启边录边传，有一定概率弹幕文件提示文件被占用导致无法转换名称，导致无法自动渲染弹幕视频

[2023-12-20 14:50:25,989][ERROR]: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: './直播回放\\[正在录制]德云色-20231220-135027-Part000.ass' -> './直播回放\\老实憨厚的笑笑-2023年12月20日13点50分25秒.ass'
[2023-12-20 14:50:25,992][ERROR]: 弹幕 ./直播回放\[正在录制]德云色-20231220-135027-Part000.ass 分段失败.
[2023-12-20 14:50:26,023][INFO]: 分片 ./直播回放\老实憨厚的笑笑-2023年12月20日13点50分25秒.flv 录制完成.
[2023-12-20 14:50:26,030][INFO]: 添加分片 ./直播回放\老实憨厚的笑笑-2023年12月20日13点50分25秒.flv 至渲染队列.
[2023-12-20 14:50:26,034][INFO]: 正在渲染: ./直播回放\老实憨厚的笑笑-2023年12月20日13点50分25秒.flv
[2023-12-20 14:50:26,040][ERROR]: 不存在弹幕文件 ./直播回放\老实憨厚的笑笑-2023年12月20日13点50分25秒.ass，跳过渲染.
Traceback (most recent call last):
  File "Z:\DanmakuRender\DMR\Render\__init__.py", line 100, in _render_subprocess
    status, info = target_render.render_one(**task.copy())
  File "Z:\DanmakuRender\DMR\Render\ffmpegrender.py", line 123, in render_one
    raise RuntimeError(f'不存在弹幕文件 {danmaku}，跳过渲染.')
RuntimeError: 不存在弹幕文件 ./直播回放\老实憨厚的笑笑-2023年12月20日13点50分25秒.ass，跳过渲染.
[2023-12-20 14:50:26,062][ERROR]: 分片 ./直播回放（带弹幕版）\老实憨厚的笑笑-2023年12月20日13点50分25秒（带弹幕版）.mp4 渲染错误.
[2023-12-20 14:50:26,065][ERROR]: 不存在弹幕文件 ./直播回放\老实憨厚的笑笑-2023年12月20日13点50分25秒.ass，跳过渲染.
[2023-12-20 14:50:26,684][ERROR]: 'AssWriter' object has no attribute '_track_tails'
Traceback (most recent call last):
  File "Z:\DanmakuRender\DMR\Downloader\__init__.py", line 215, in start_helper
    self.start_once()
  File "Z:\DanmakuRender\DMR\Downloader\__init__.py", line 176, in start_once
    return future.result()
  File "C:\Users\admin\.conda\envs\d2l\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\admin\.conda\envs\d2l\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\admin\.conda\envs\d2l\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "Z:\DanmakuRender\DMR\Downloader\__init__.py", line 148, in danmaku_thread
    self.dmw.start(self_segment=not self.video)
  File "Z:\DanmakuRender\DMR\Downloader\danmakuio.py", line 75, in start
    return self.start_dmc()
  File "Z:\DanmakuRender\DMR\Downloader\danmakuio.py", line 171, in start_dmc
    asyncio.get_event_loop().run_until_complete(danmu_monitor())
  File "C:\Users\admin\.conda\envs\d2l\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "Z:\DanmakuRender\DMR\Downloader\danmakuio.py", line 136, in danmu_monitor
    if self.dmwriter.add(danmu):
  File "Z:\DanmakuRender\DMR\Downloader\asswriter.py", line 134, in add
    self._track_tails[tid] = danmu
AttributeError: 'AssWriter' object has no attribute '_track_tails'

**Comment by chenfanz** [comment]
这周每天会遇到一次这种报错

**Comment by SmallPeaches** [comment]
按道理来说边录边传是没有影响的，应该是程序没有及时释放文件导致的。我之后修复一下这个问题。
