### ISSUE TITLE
V4安装后报错，无法使用，还请大神指导一下

### ISSUE THREAD

**Issue by hahadawang666** [SmallPeaches/DanmakuRender#18]
[2023-02-03 18:39:48,247][ERROR]: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "G:\DanmakuRender-4\DMR\Downloader\__init__.py", line 152, in start_helper
    self.start_once()
  File "G:\DanmakuRender-4\DMR\Downloader\__init__.py", line 100, in start_once
    width, height = FFprobe.get_resolution(stream_url,stream_request_header)
  File "G:\DanmakuRender-4\DMR\utils.py", line 45, in get_resolution
    out = subprocess.check_output([
  File "E:\Program\Python\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "E:\Program\Python\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\Program\Python\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\Program\Python\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
[2023-02-03 18:39:48,248][ERROR]: 'Downloader' object has no attribute 'dmw'
Traceback (most recent call last):
  File "G:\DanmakuRender-4\DMR\Downloader\__init__.py", line 152, in start_helper
    self.start_once()
  File "G:\DanmakuRender-4\DMR\Downloader\__init__.py", line 100, in start_once
    width, height = FFprobe.get_resolution(stream_url,stream_request_header)
  File "G:\DanmakuRender-4\DMR\utils.py", line 45, in get_resolution
    out = subprocess.check_output([
  File "E:\Program\Python\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "E:\Program\Python\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\Program\Python\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\Program\Python\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\DanmakuRender-4\DMR\Downloader\__init__.py", line 182, in stop_once
    self.dmw.stop()
AttributeError: 'Downloader' object has no attribute 'dmw'
[2023-02-03 18:39:48,248][ERROR]: 'Downloader' object has no attribute 'downloader'
Traceback (most recent call last):
  File "G:\DanmakuRender-4\DMR\Downloader\__init__.py", line 152, in start_helper
    self.start_once()
  File "G:\DanmakuRender-4\DMR\Downloader\__init__.py", line 100, in start_once
    width, height = FFprobe.get_resolution(stream_url,stream_request_header)
  File "G:\DanmakuRender-4\DMR\utils.py", line 45, in get_resolution
    out = subprocess.check_output([
  File "E:\Program\Python\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "E:\Program\Python\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\Program\Python\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\Program\Python\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\DanmakuRender-4\DMR\Downloader\__init__.py", line 186, in stop_once
    self.downloader.stop()

**Comment by SmallPeaches** [comment]
ffmpeg没安装好吧

**Comment by hahadawang666** [comment]
我把ffmpeg放在了tools文件夹里的，还需要调整哪里吗

**Comment by SmallPeaches** [comment]
一共有三个文件，FFmpeg ffprobe 还有 ffplay，都放进去了吗？

**Comment by hahadawang666** [comment]
刚把差的ffplay放入后还是报错
[2023-02-03 18:50:03,330][ERROR]: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "G:\DanmakuRender-4\DMR\Downloader\__init__.py", line 152, in start_helper
    self.start_once()
  File "G:\DanmakuRender-4\DMR\Downloader\__init__.py", line 100, in start_once
    width, height = FFprobe.get_resolution(stream_url,stream_request_header)
  File "G:\DanmakuRender-4\DMR\utils.py", line 45, in get_resolution
    out = subprocess.check_output([
  File "E:\Program\Python\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "E:\Program\Python\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\Program\Python\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\Program\Python\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
[2023-02-03 18:50:03,331][ERROR]: 'Downloader' object has no attribute 'dmw'
Traceback (most recent call last):
  File "G:\DanmakuRender-4\DMR\Downloader\__init__.py", line 152, in start_helper
    self.start_once()
  File "G:\DanmakuRender-4\DMR\Downloader\__init__.py", line 100, in start_once
    width, height = FFprobe.get_resolution(stream_url,stream_request_header)
  File "G:\DanmakuRender-4\DMR\utils.py", line 45, in get_resolution
    out = subprocess.check_output([
  File "E:\Program\Python\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "E:\Program\Python\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\Program\Python\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\Program\Python\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\DanmakuRender-4\DMR\Downloader\__init__.py", line 182, in stop_once
    self.dmw.stop()
AttributeError: 'Downloader' object has no attribute 'dmw'
[2023-02-03 18:50:03,332][ERROR]: 'Downloader' object has no attribute 'downloader'
Traceback (most recent call last):
  File "G:\DanmakuRender-4\DMR\Downloader\__init__.py", line 152, in start_helper
    self.start_once()
  File "G:\DanmakuRender-4\DMR\Downloader\__init__.py", line 100, in start_once
    width, height = FFprobe.get_resolution(stream_url,stream_request_header)
  File "G:\DanmakuRender-4\DMR\utils.py", line 45, in get_resolution
    out = subprocess.check_output([
  File "E:\Program\Python\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "E:\Program\Python\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\Program\Python\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\Program\Python\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\DanmakuRender-4\DMR\Downloader\__init__.py", line 186, in stop_once
    self.downloader.stop()

**Comment by SmallPeaches** [comment]
那你可能要在配置文件里面把FFmpeg的路径指定一下：
```yaml
ffmpeg: ./tools/ffmpeg.exe
ffprobe: ./tools/ffprobe.exe
```

**Comment by hahadawang666** [comment]
感谢回复，现在可以录制了，请问V4还有没有不自动渲染弹幕，只下载的命令呀

**Comment by SmallPeaches** [comment]
可以的，default.yml里面配置一下

**Comment by hahadawang666** [comment]
好的，感谢感谢！
