### ISSUE TITLE
Linux安装一直卡在最后一步 求详解下

### ISSUE THREAD

**Issue by LoveDqi** [SmallPeaches/DanmakuRender#205]
按照Windows的安装方法将biliup放在了tools文件夹里面 运行的时候出现报错无法运行
[2024-04-06 19:29:15,015][INFO]: 正在启动测试
Traceback (most recent call last):
  File "/DanmakuRender-2024.1.30/DanmakuRender-2024.1.30/dryrun.py", line 68, in <module>
    dmr.start()
  File "/DanmakuRender-2024.1.30/DanmakuRender-2024.1.30/DMR/__init__.py", line 39, in start
    self.uploader = Uploader(
  File "/DanmakuRender-2024.1.30/DanmakuRender-2024.1.30/DMR/Uploader/__init__.py", line 32, in __init__
    uploader = biliuprs(debug=self.debug, **upd_conf)
  File "/DanmakuRender-2024.1.30/DanmakuRender-2024.1.30/DMR/Uploader/biliuprs.py", line 31, in __init__
    if not self.islogin():
  File "/DanmakuRender-2024.1.30/DanmakuRender-2024.1.30/DMR/Uploader/biliuprs.py", line 102, in islogin
    proc = subprocess.Popen(renew_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, bufsize=10**8)
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'tools/biliup'

**Comment by SmallPeaches** [comment]
你没给执行权限，输入`chmod +x tools/biliup`修改权限

**Comment by blackedxyz** [comment]
sudo -i
切换到root账号

**Comment by LoveDqi** [comment]
给了执行权限可以了，谢谢
