### ISSUE TITLE
ffmpeg退出一下什么意思？？

### ISSUE THREAD

**Issue by blackedxyz** [SmallPeaches/DanmakuRender#208]
[2024-04-07 20:14:54,269][ERROR]: 录制 杨长顺维修家 遇到错误，即将重试.
[2024-04-07 20:14:54,270][ERROR]: FFmpeg 退出.
[2024-04-07 20:14:54,583][INFO]: 杨长顺维修家 录制开始.
[2024-04-07 20:16:07,247][ERROR]: FFmpeg 退出.
Traceback (most recent call last):
  File "C:\Users\Administrator\DanmakuRender-2024.1.30\DanmakuRender-4\DMR\Downloader\__init__.py", line 215, in start_helper
    self.start_once()
  File "C:\Users\Administrator\DanmakuRender-2024.1.30\DanmakuRender-4\DMR\Downloader\__init__.py", line 176, in start_once
    return future.result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrator\DanmakuRender-2024.1.30\DanmakuRender-4\DMR\Downloader\__init__.py", line 164, in video_thread
    self.downloader.start()
  File "C:\Users\Administrator\DanmakuRender-2024.1.30\DanmakuRender-4\DMR\Downloader\ffmpegio.py", line 248, in start
    return self.start_helper()
  File "C:\Users\Administrator\DanmakuRender-2024.1.30\DanmakuRender-4\DMR\Downloader\ffmpegio.py", line 159, in start_helper
    raise RuntimeError(f'FFmpeg 退出.')

**Comment by SmallPeaches** [comment]
如果是偶尔是正常的，如果经常出现你打开日志文件看看对应时间的具体的报错信息是什么。
