### ISSUE TITLE
弹幕录制报错

### ISSUE THREAD

**Issue by MoncozGC** [SmallPeaches/DanmakuRender#240]
请教一下 弹幕的录制是不是有问题了呢

日志如下
```log
[2024-05-30 17:32:11][ERROR] 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "G:\CodeProject\DanmakuRender_off\DMR\Downloader\danmakuio.py", line 135, in dmc_task
    await dmc.start()
  File "G:\CodeProject\DanmakuRender_off\DMR\LiveAPI\danmaku\__init__.py", line 96, in start
    await self.init_ws()
  File "G:\CodeProject\DanmakuRender_off\DMR\LiveAPI\danmaku\__init__.py", line 53, in init_ws
    ws_url, reg_datas = await self.__site_api.get_ws_info(self.__url)
  File "G:\CodeProject\DanmakuRender_off\DMR\LiveAPI\danmaku\huya.py", line 26, in get_ws_info
    j = json.loads(m.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
[2024-05-30 17:32:12][ERROR] 弹幕下载线程异常退出，正在重试...
```

**Comment by yigeliu001** [comment]
抖音录制弹幕也报错了
日志：
[2024-10-04 18:53:46,988][ERROR]: 200, message='Invalid response status', url='wss://webcast3-ws-web-lf.douyin.com/webcast/im/push/v2/?room_id=7421841079764405019&compress=gzip&signature=00000000&aid=6383&device_platform=web&browser_language=zh-CN&browser_platform=Win32&browser_name=Chrome&browser_version=92.0.4515.159'
Traceback (most recent call last):
  File "D:\桌面\DanmakuRender-2024.05.30\DMR\Downloader\danmakuio.py", line 112, in dmc_task
    await dmc.start()
  File "D:\桌面\DanmakuRender-2024.05.30\DMR\LiveAPI\danmaku\__init__.py", line 96, in start
    await self.init_ws()
  File "D:\桌面\DanmakuRender-2024.05.30\DMR\LiveAPI\danmaku\__init__.py", line 54, in init_ws
    self.__ws = await self.__hs.ws_connect(ws_url, headers=self.__site_api.headers)
  File "C:\Users\26321\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 949, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 200, message='Invalid response status', url='wss://webcast3-ws-web-lf.douyin.com/webcast/im/push/v2/?room_id=7421841079764405019&compress=gzip&signature=00000000&aid=6383&device_platform=web&browser_language=zh-CN&browser_platform=Win32&browser_name=Chrome&browser_version=92.0.4515.159'
[2024-10-04 18:53:47,057][ERROR]: 弹幕下载线程异常退出，正在重试...
