### ISSUE TITLE
能录制不带弹幕的直播回放，但有报错，ctrl+c退出后，使用render_only提示：渲染错误, fileno

### ISSUE THREAD

**Issue by LeonaWu** [SmallPeaches/DanmakuRender#260]
因为一直有报错升级了版本5，录制抖音直播的时候提示：

raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 200, message='Invalid response status', url=URL('wss://webcast3-ws-web-lf.douyin.com/webcast/im/push/v2/?room_id=-------------&compress=gzip&signature=0000----0&aid=63--&device_platform=web&browser_language=zh-CN&browser_platform=Win32&browser_name=Chrome&browser_version=92.0.4515.159')
[2024-06-22 00:02:22,768][error]: 弹幕下载线程异常退出，正在重试...
[2024-06-22 00:02:22,768][error]: 弹幕下载线程异常退出，正在重试...

ctrl+c退出后，发现直播回放文件夹有录制的.ass和.flv文件，随后用render_only单独渲染，报错：

[2024-06-22 00:06:02,682][error]: fileno
Traceback (most recent call last):
  File "g:\danmakurender-5\render_only.py", line 125, in <module>
    main()
  File "g:\danmakurender-5\render_only.py", line 116, in main
    status, info = target_render.render_one(video=video, output=task['output'])
  File "G:\DanmakuRender-5\DMR\Render\dmrender.py", line 95, in render_one
    status, info = self.render_helper(video.path, danmaku, output, **kwargs)
  File "G:\DanmakuRender-5\DMR\Render\dmrender.py", line 80, in render_helper
    return self.raw_ffmpeg.call_ffmpeg(ffmpeg_args)
  File "G:\DanmakuRender-5\DMR\Render\ffmpeg.py", line 27, in call_ffmpeg
    self.render_proc = subprocess.Popen(
  File "C:\Users\fan\Anaconda2\envs\py3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 109, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)
  File "C:\Users\fan\Anaconda2\envs\py3\lib\subprocess.py", line 829, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Users\fan\Anaconda2\envs\py3\lib\subprocess.py", line 1284, in _get_handles
    c2pwrite = msvcrt.get_osfhandle(stdout.fileno())
  File "C:\Users\fanAnaconda2\envs\py3\lib\site-packages\ipykernel\iostream.py", line 370, in fileno
    raise io.UnsupportedOperation(msg)
io.UnsupportedOperation: fileno
渲染错误, fileno

请教一下，这个渲染错误是什么原因呢？谢谢回复。

**Comment by SmallPeaches** [comment]
这个ass文件里面没有内容的，所以报错也正常

**Comment by LeonaWu** [comment]
好的，谢谢大佬，用别的查看了下字幕文件发现里面确实没有具体的弹幕信息。
