### ISSUE TITLE
抖音直播链接带点无法录制

### ISSUE THREAD

**Issue by yibingchaoyue** [SmallPeaches/DanmakuRender#295]
即将添加以下配置文件：['configs\\replay-1.yml']
[2024-08-09 10:42:30,285][INFO]: 添加直播：https://live.douyin.com/888ywy888.
Traceback (most recent call last):
  File "C:\ChronoDownloads\DanmakuRender-2024.05.30\DanmakuRender-2024.05.30\DMR\LiveAPI\douyin.py", line 58, in __init__
    self.real_rid = resp['data'][0]['id_str']
                    ~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ChronoDownloads\DanmakuRender-2024.05.30\DanmakuRender-2024.05.30\main.py", line 101, in <module>
    dmr.start()
  File "C:\ChronoDownloads\DanmakuRender-2024.05.30\DanmakuRender-2024.05.30\DMR\__init__.py", line 57, in start
    downloader = Downloader(
                 ^^^^^^^^^^^
  File "C:\ChronoDownloads\DanmakuRender-2024.05.30\DanmakuRender-2024.05.30\DMR\Downloader\__init__.py", line 37, in __init__
    self.liveapi = LiveAPI(self.plat, self.rid)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ChronoDownloads\DanmakuRender-2024.05.30\DanmakuRender-2024.05.30\DMR\LiveAPI\__init__.py", line 23, in __init__
    self.api_class = douyin(rid=self.rid)
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\ChronoDownloads\DanmakuRender-2024.05.30\DanmakuRender-2024.05.30\DMR\LiveAPI\douyin.py", line 60, in __init__
    raise Exception(f'解析抖音房间号{rid}错误.')
Exception: 解析抖音房间号888ywy888错误.

**Comment by SmallPeaches** [comment]
你试下输它的标准数字直播间号看看？

**Comment by yibingchaoyue** [comment]
> 你试下输它的标准数字直播间号看看？
标准的可以，但每次得开播才知道标准的房间号，有时候想录看见的主播，又是小数点结尾就不太好录，应该就是小数点的问题

**Comment by SmallPeaches** [comment]
最近实验发现主播的数字抖音号就是标准直播间号？你可以试下看看
