### ISSUE TITLE
虎牙录屏出现：无法获取视频大小，使用默认值[1920，1080]  FFrpeg 自动退出；疑似无法获取直播流问题

### ISSUE THREAD

**Issue by zuoluo24** [SmallPeaches/DanmakuRender#299]
![Uploading 1212.png…]()

**Comment by zuoluo24** [comment]
[2024-08-23 16:05:40,030][info]: 下载任务 tsl 已启动。
[2024-08-23 16:05:40,354][info]: tsl: 直播开始
[2024-08-23 16:05:42,413][warning]: 无法获取视频大小，使用默认值 [1920, 1080].
[2024-08-23 16:05:43,532][error]: FFmpeg 退出.
Traceback (most recent call last):
  File "F:\个人\录屏\DanmakuRender-5\DanmakuRender-5 - tsl\DMR\Downloader\stream_downloader.py", line 245, in start_helper
    self.start_once()
  File "F:\个人\录屏\DanmakuRender-5\DanmakuRender-5 - tsl\DMR\Downloader\stream_downloader.py", line 204, in start_once
    return future.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\个人\录屏\DanmakuRender-5\DanmakuRender-5 - tsl\DMR\Downloader\stream_downloader.py", line 192, in video_thread
    self.downloader.start()
  File "F:\个人\录屏\DanmakuRender-5\DanmakuRender-5 - tsl\DMR\Downloader\ffmpeg.py", line 203, in start
    return self.start_helper()
  File "F:\个人\录屏\DanmakuRender-5\DanmakuRender-5 - tsl\DMR\Downloader\ffmpeg.py", line 124, in start_helper
    raise RuntimeError(f'FFmpeg 退出.')
RuntimeError: FFmpeg 退出.
[2024-08-23 16:05:43,536][info]: tsl: 录制过程出错:FFmpeg 退出.
[2024-08-23 16:05:43,632][info]: tsl: 直播开始
[2024-08-23 16:05:44,359][warning]: 无法获取视频大小，使用默认值 [1920, 1080].
[

**Comment by SmallPeaches** [comment]
试下换个cdn？
