### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by q1518001822** [SmallPeaches/DanmakuRender#316]
[2024-10-10 20:44:54,127][ERROR]: 'FFmpegDownloader' object has no attribute 'ffmpeg_proc'
Traceback (most recent call last):
  File "C:\直播复盘录制工具_N\DanmakuRender-2024.05.30\DanmakuRender-2024.05.30\DMR\Downloader\ffmpegio.py", line 265, in stop
    out, _ = self.ffmpeg_proc.communicate('q',timeout=3)
AttributeError: 'FFmpegDownloader' object has no attribute 'ffmpeg_proc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\直播复盘录制工具_N\DanmakuRender-2024.05.30\DanmakuRender-2024.05.30\DMR\Downloader\__init__.py", line 252, in stop_once
    self.downloader.stop()
  File "C:\直播复盘录制工具_N\DanmakuRender-2024.05.30\DanmakuRender-2024.05.30\DMR\Downloader\ffmpegio.py", line 269, in stop
    self.ffmpeg_proc.kill()
AttributeError: 'FFmpegDownloader' object has no attribute 'ffmpeg_proc'
[2024-10-10 20:44:54,128][INFO]: 录制完成，请检查录制文件

**Comment by SmallPeaches** [comment]
用其他录制引擎试试
