### ISSUE TITLE
视频下载出错

### ISSUE THREAD

**Issue by cena1001** [SmallPeaches/DanmakuRender#323]
遇到下面的问题，不知道是什么原因哇

[2024-11-06 23:22:43,374][error]: 下载 https://space.bilibili.com/1123123132 时出现错误:  WARN  以非大会员身份登录，注意无法下载会员专享剧集喔～
Traceback (most recent call last):
  File "D:\software\WORK\env\miniconda\envs\DanmakuRender-5\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\software\WORK\env\miniconda\envs\DanmakuRender-5\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\software\WORK\env\miniconda\envs\DanmakuRender-5\Scripts\yutto.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\software\WORK\env\miniconda\envs\DanmakuRender-5\lib\site-packages\yutto\__main__.py", line 55, in main
    args_list = flatten_args(args, parser)
  File "D:\software\WORK\env\miniconda\envs\DanmakuRender-5\lib\site-packages\yutto\__main__.py", line 203, in flatten_args
    validate_basic_arguments(args)
  File "D:\software\WORK\env\miniconda\envs\DanmakuRender-5\lib\site-packages\yutto\validator.py", line 73, in validate_basic_arguments
    ffmpeg = FFmpeg()
  File "D:\software\WORK\env\miniconda\envs\DanmakuRender-5\lib\site-packages\yutto\utils\funcutils\singleton.py", line 31, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
  File "D:\software\WORK\env\miniconda\envs\DanmakuRender-5\lib\site-packages\yutto\utils\ffmpeg.py", line 25, in __init__
    raise FFmpegNotFoundError from None
yutto.utils.ffmpeg.FFmpegNotFoundError: 请配置正确的 FFmpeg 路径

**Comment by SmallPeaches** [comment]
请参考yutto官方文档：https://bilili.nyakku.moe/guide/getting-started.html#%E6%88%91%E7%9A%84%E4%BE%9D%E8%B5%96-ffmpeg
