### ISSUE TITLE
抖音录制弹幕文件是空的

### ISSUE THREAD

**Issue by actuallyidont** [SmallPeaches/DanmakuRender#331]
![Screenshot 2024-11-11 143351](https://github.com/user-attachments/assets/60b9b3a4-6b38-4909-b38d-555ea99276ed)
有什么解决方法吗？提前谢谢了

**Comment by actuallyidont** [comment]
![Screenshot 2024-11-11 143942](https://github.com/user-attachments/assets/3ecd4059-6f90-43d1-842c-af573ea37401)

**Comment by SmallPeaches** [comment]
用v5

**Comment by actuallyidont** [comment]
是用的v5

**Comment by SmallPeaches** [comment]
看下控制台报错信息，或者换个网络环境和主播试试

**Comment by actuallyidont** [comment]
![Screenshot 2024-11-11 195251](https://github.com/user-attachments/assets/6e9e9e65-1721-4acf-857a-745465070876)

**Comment by actuallyidont** [comment]
[2024-11-11 19:48:09,190][error]: 200, message='Invalid response status', url='wss://webcast5-ws-web-lf.douyin.com/webcast/im/push/v2/?room_id=7435978481701309222&compress=gzip&version_code=180800&webcast_sdk_version=1.0.14-beta.0&live_id=1&did_rule=3&user_unique_id=7776283672358909005&identity=audience&signature=0&aid=6383&device_platform=web&browser_language=zh-CN&browser_platform=Win32&browser_name=Mozilla&browser_version=92.0.4515.159'
Traceback (most recent call last):
  File "/root/DanmakuRender-5/DMR/Downloader/Danmaku/danmaku.py", line 146, in dmc_task
    await dmc.start()
  File "/root/DanmakuRender-5/DMR/LiveAPI/danmaku/__init__.py", line 124, in start
    await self.init_ws()
  File "/root/DanmakuRender-5/DMR/LiveAPI/danmaku/__init__.py", line 77, in init_ws
    self.__ws = await self.__hs.ws_connect(
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/aiohttp/client.py", line 947, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 200, message='Invalid response status', url='wss://webcast5-ws-web-lf.douyin.com/webcast/im/push/v2/?room_id=7435978481701309222&compress=gzip&version_code=180800&webcast_sdk_version=1.0.14-beta.0&live_id=1&did_rule=3&user_unique_id=7776283672358909005&identity=audience&signature=0&aid=6383&device_platform=web&browser_language=zh-CN&browser_platform=Win32&browser_name=Mozilla&browser_version=92.0.4515.159'
error:DMR.Downloader.Danmaku.danmaku:200, message='Invalid response status', url='wss://webcast5-ws-web-lf.douyin.com/webcast/im/push/v2/?room_id=7435978481701309222&compress=gzip&version_code=180800&webcast_sdk_version=1.0.14-beta.0&live_id=1&did_rule=3&user_unique_id=7776283672358909005&identity=audience&signature=0&aid=6383&device_platform=web&browser_language=zh-CN&browser_platform=Win32&browser_name=Mozilla&browser_version=92.0.4515.159'
Traceback (most recent call last):
  File "/root/DanmakuRender-5/DMR/Downloader/Danmaku/danmaku.py", line 146, in dmc_task
    await dmc.start()
  File "/root/DanmakuRender-5/DMR/LiveAPI/danmaku/__init__.py", line 124, in start
    await self.init_ws()
  File "/root/DanmakuRender-5/DMR/LiveAPI/danmaku/__init__.py", line 77, in init_ws
    self.__ws = await self.__hs.ws_connect(
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/aiohttp/client.py", line 947, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 200, message='Invalid response status', url='wss://webcast5-ws-web-lf.douyin.com/webcast/im/push/v2/?room_id=7435978481701309222&compress=gzip&version_code=180800&webcast_sdk_version=1.0.14-beta.0&live_id=1&did_rule=3&user_unique_id=7776283672358909005&identity=audience&signature=0&aid=6383&device_platform=web&browser_language=zh-CN&browser_platform=Win32&browser_name=Mozilla&browser_version=92.0.4515.159'
[2024-11-11 19:48:09,229][error]: 弹幕下载线程异常退出，正在重试...
error:DMR.Downloader.Danmaku.danmaku:弹幕下载线程异常退出，正在重试...
debug:DMR.Downloader.Danmaku.danmaku:None
error:root:获取抖音弹幕URL签名失败.

**Comment by SmallPeaches** [comment]
你试下用自己抖音的cookies看看，参考https://github.com/SmallPeaches/DanmakuRender/issues/258
