### ISSUE TITLE
运行出现问题

### ISSUE THREAD

**Issue by RAINighty** [SmallPeaches/DanmakuRender#41]
```
Traceback (most recent call last):
  File "F:\DanmakuRender-4\main.py", line 62, in <module>
    config = utils.Config(default_config,replay_config)
  File "F:\DanmakuRender-4\DMR\utils.py", line 131, in __init__
    plat, _ = split_url(rep['url'])
KeyError: 'url'
```
replay.yml
```
replay:
  - url: https://live.bilibili.com/5050
  - segement: 7200
    upload:
      dm_video: bilibili
```

**Comment by SmallPeaches** [comment]
同一个录制不同参数不要前面这个`-`
```yaml
replay:
  - url: https://live.bilibili.com/5050
    segement: 7200
    upload:
      dm_video: bilibili
```

**Comment by RAINighty** [comment]
已解决
