### ISSUE TITLE
户外主播意外下播(不是手动关播)有概率不能自动开启录制,可能是自动重试次数太多,循环关闭了

### ISSUE THREAD

**Issue by latv666** [SmallPeaches/DanmakuRender#51]
意外下播,比如手机没电,直接关机,几个小时内没法开机

这是我的设置

  - url: https://www.huya.com/111
    output_name: '111_直播录像_{YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}'
    check_stream_changes: False
    auto_render: False
    disable_lowspeed_interrupt: True
    engine: streamgears   # 使用streamgears作为下载引擎
    vid_format: flv       # 使用streamgears作为下载引擎时，录制格式只能是flv
    output_dir: ./直播回放/111

这是正常直播期间未知原因的报错

[2023-05-13 15:14:15,563][ERROR]: Stream-gears 异常退出 .
Traceback (most recent call last):
  File "E:\DMR_record_flv\DMR\Downloader\__init__.py", line 175, in start_helper
    self.start_once()
  File "E:\DMR_record_flv\DMR\Downloader\__init__.py", line 142, in start_once
    return future.result()
  File "C:\Users\hosts\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Users\hosts\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Users\hosts\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\DMR_record_flv\DMR\Downloader\__init__.py", line 130, in video_thread
    self.downloader.start()
  File "E:\DMR_record_flv\DMR\Downloader\streamgearsio.py", line 109, in start
    return self.start_helper()
  File "E:\DMR_record_flv\DMR\Downloader\streamgearsio.py", line 106, in start_helper
    raise RuntimeError(f'Stream-gears 异常退出 {line}.')
RuntimeError: Stream-gears 异常退出 .

反复相同报错后的另一个报错,此后不再自动录制

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0374B538>
Traceback (most recent call last):
  File "C:\Users\hosts\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\hosts\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\hosts\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\hosts\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by NoColorPiggg** [comment]
是的 我也遇到了这个问题

**Comment by SmallPeaches** [comment]
从这里没看出来什么问题，你看下日志里面有没有一直请求开播信息（会有`Starting new HTTPS connection`字样）

**Comment by SmallPeaches** [comment]
如果方便的话发日志文件过来是最好的

**Comment by NoColorPiggg** [comment]
[DMR-20230513.log](https://github.com/SmallPeaches/DanmakuRender/files/11471662/DMR-20230513.log)

**Comment by SmallPeaches** [comment]
> [DMR-20230513.log](https://github.com/SmallPeaches/DanmakuRender/files/11471662/DMR-20230513.log)

你这个最后弹幕是正常的吗？就最后一个弹幕文件包括了下播前所有的弹幕，但是没有视频

**Comment by NoColorPiggg** [comment]
弹幕我回家看看吧 可能已经被我删了

发自我的iPhone

**Comment by latv666** [comment]
> > [DMR-20230513.log](https://github.com/SmallPeaches/DanmakuRender/files/11471662/DMR-20230513.log)
> 
> 你这个最后弹幕是正常的吗？就最后一个弹幕文件包括了下播前所有的弹幕，但是没有视频

我的日志跟 nocolorpiggg 差不多,有非常多的请求开播信息
弹幕和视频都删了= =弹幕大约是 300B一个,视频大约是 700B,下次遇到一定保护好现场

**Comment by latv666** [comment]
> > [DMR-20230513.log](https://github.com/SmallPeaches/DanmakuRender/files/11471662/DMR-20230513.log)
> 
> 你这个最后弹幕是正常的吗？就最后一个弹幕文件包括了下播前所有的弹幕，但是没有视频

bug 重现了,下面是日志和截图,截图里的视频无法播放,每个字幕文件只有一行弹幕,命令行里面反复提示 stream-gears 异常退出

[DMR-20230520.log](https://github.com/SmallPeaches/DanmakuRender/files/11523793/DMR-20230520.log)

![image](https://github.com/SmallPeaches/DanmakuRender/assets/1801723/f59e07df-99a1-40bd-a0c2-4ccdbd5dc7e4)

**Comment by SmallPeaches** [comment]
这个好像是因为stream-gears返回错误了，你ffmpeg下载有这个问题吗？
![1684734283743](https://github.com/SmallPeaches/DanmakuRender/assets/65701756/3e03d254-0404-45b8-b4f4-bb651da73b2b)

**Comment by latv666** [comment]
> 这个好像是因为stream-gears返回错误了，你ffmpeg下载有这个问题吗？ ![1684734283743](https://user-images.githubusercontent.com/65701756/239813178-3e03d254-0404-45b8-b4f4-bb651da73b2b.png)

报错的时候试过 ffmpeg,是没问题的,这个 stream gears 很奇怪,过一阵自己恢复,但具体原因不明,附上日志,弹幕和视频

[DMR-20230521.log](https://github.com/SmallPeaches/DanmakuRender/files/11529422/DMR-20230521.log)

![image](https://github.com/SmallPeaches/DanmakuRender/assets/1801723/90892f5d-179c-418f-8f2a-a56e623d8018)

**Comment by SmallPeaches** [comment]
stream-gears有些时候是有奇奇怪怪的问题，如果你录制的主播是PC直播这种比较稳定的话建议还是用ffmpeg

**Comment by NoColorPiggg** [comment]
我现在目前录PC直播就是用的换新引擎之前的老版本。不知道新版本如果关闭检测视频流变化的话，意外断播再开播（例如掉网）这种情况会不会自动开始录制，还是一刀切全不检测了。

发自我的iPhone

**Comment by SmallPeaches** [comment]
如果要是关了的话就得等ffmpeg 检测到断流退出才停
