### ISSUE TITLE
大佬新版渲染报错，不知是什么情况

### ISSUE THREAD

**Issue by NoColorPiggg** [SmallPeaches/DanmakuRender#63]
Traceback (most recent call last):
  File "main.py", line 82, in <module>
    render.render_only(input_dir)
  File "G:\Dajiuge\DMR\Render\__init__.py", line 129, in render_only
    'output':output
  File "G:\Dajiuge\DMR\Render\ffmpegrender.py", line 77, in render_one
    self.render_helper(video,danmaku,output,to_stdout=self.debug,logfile=logfile)
  File "G:\Dajiuge\DMR\Render\ffmpegrender.py", line 31, in render_helper
    self.fps = float(FFprobe.run_ffprobe(video)['streams'][0]['avg_frame_rate'].split('/')[0]) / float(FFprobe.run_ffprobe(video)['streams'][0]['avg_frame_rate'].split('/')[1])
ZeroDivisionError: float division by zero
PS G:\Dajiuge>

**Comment by SmallPeaches** [comment]
好像是新版的问题，你先回退一下，等下我研究一下怎么修复

**Comment by NoColorPiggg** [comment]
嗯啊，好像就是昨天的版本更新后出现的问题

发自我的iPhone

**Comment by SmallPeaches** [comment]
已经推送更新
