### ISSUE TITLE
抖音某些直播间录制出错

### ISSUE THREAD

**Issue by justdoiting** [SmallPeaches/DanmakuRender#64]
logs如下

[2023-06-01 23:17:44,253][ffmpegio][DEBUG]: Command '['ffmpeg', '-y', '-headers', 'Content-Type: application/x-www-form-urlencoded\r\nUser-Agent: Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Mobile Safari/537.36 \r\n', '-fflags', '+discardcorrupt', '-reconnect', '1', '-rw_timeout', '10000000', '-analyzeduration', '15000000', '-probesize', '50000000', '-thread_queue_size', '16', '-i', 'http://pull-flv-l11.douyincdn.com/stage/stream-689581545787490449_or4.flv?expire=1686237412&sign=2baa15c477c8fd5610fd85c9464e110c', '-c', 'copy', '-f', 'segment', '-segment_time', '36000', '-reset_timestamps', '1', '-movflags', 'faststart+frag_keyframe+empty_moov', './直播回放\\小薛-20230601-231715-Part%03d.ts']' timed out after 3 seconds
[2023-06-01 23:17:44,253][__init__][ERROR]: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "E:\DanmakuRender-4\DMR\Downloader\__init__.py", line 175, in start_helper
    self.start_once()
  File "E:\DanmakuRender-4\DMR\Downloader\__init__.py", line 142, in start_once
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Program Files\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\DanmakuRender-4\DMR\Downloader\__init__.py", line 130, in video_thread
    self.downloader.start()
  File "E:\DanmakuRender-4\DMR\Downloader\ffmpegio.py", line 213, in start
    return self.start_helper()
           ^^^^^^^^^^^^^^^^^^^
  File "E:\DanmakuRender-4\DMR\Downloader\ffmpegio.py", line 164, in start_helper
    raise RuntimeError(f'{self.taskname} 管道读取错误, 即将重试.')
RuntimeError: 小薛 管道读取错误, 即将重试.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DanmakuRender-4\DMR\Downloader\__init__.py", line 210, in stop_once
    self.downloader.stop()
  File "E:\DanmakuRender-4\DMR\Downloader\ffmpegio.py", line 241, in stop
    self.callback(self.thisfile)
  File "E:\DanmakuRender-4\DMR\Downloader\__init__.py", line 52, in segment_callback
    if self.segment_info is None or not exists(filename):
                                        ^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
[2023-06-01 23:17:44,258][__init__][DEBUG]: PIPE MESSAGE: {'src': 'downloader', 'msg': 'restart', 'type': 'error', 'group': '小薛', 'desc': RuntimeError('小薛 管道读取错误, 即将重试.')}
[2023-06-01 23:17:44,258][__init__][ERROR]: 录制 小薛 遇到错误，即将重试.
[2023-06-01 23:17:44,258][__init__][ERROR]: 小薛 管道读取错误, 即将重试.
[2023-06-01 23:17:44,259][connectionpool][DEBUG]: Starting new HTTPS connection (1): live.douyin.com:443
[2023-06-01 23:17:44,634][connectionpool][DEBUG]: https://live.douyin.com:443 "GET /42980448934 HTTP/1.1" 200 None
[2023-06-01 23:17:45,347][__init__][DEBUG]: PIPE MESSAGE: {'src': 'downloader', 'msg': 'start', 'type': 'info', 'group': '小薛'}
[2023-06-01 23:17:45,347][__init__][INFO]: 小薛 录制开始.
[2023-06-01 23:17:45,348][connectionpool][DEBUG]: Starting new HTTPS connection (1): live.douyin.com:443
[2023-06-01 23:17:45,857][connectionpool][DEBUG]: https://live.douyin.com:443 "GET /42980448934 HTTP/1.1" 200 None
[2023-06-01 23:17:46,508][connectionpool][DEBUG]: Starting new HTTPS connection (1): live.douyin.com:443
[2023-06-01 23:17:46,777][connectionpool][DEBUG]: https://live.douyin.com:443 "GET /42980448934 HTTP/1.1" 200 None

**Comment by justdoiting** [comment]
将ffmpeg.exe和ffprobe.exe移动到tools文件夹下  就好了

**Comment by justdoiting** [comment]
这个直播间在网页是正常看的，但是工具录制不了 https://live.douyin.com/42980448934

logs如下：
[2023-06-02 22:31:54,023][ffmpegio][DEBUG]: Command '['ffmpeg', '-y', '-headers', 'Content-Type: application/x-www-form-urlencoded\r\nUser-Agent: Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Mobile Safari/537.36 \r\n', '-fflags', '+discardcorrupt', '-reconnect', '1', '-rw_timeout', '10000000', '-analyzeduration', '15000000', '-probesize', '50000000', '-thread_queue_size', '16', '-i', 'http://pull-flv-l11.douyincdn.com/stage/stream-113126458679623825_or4.flv?expire=1686321065&sign=3adcbcfad5937c20dc18b0279737432f', '-c', 'copy', '-f', 'segment', '-segment_time', '36000', '-reset_timestamps', '1', '-movflags', 'faststart+frag_keyframe+empty_moov', './直播回放\\小薛-20230602-223125-Part%03d.ts']' timed out after 3 seconds
[2023-06-02 22:31:54,023][__init__][ERROR]: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "E:\DanmakuRender-4\DMR\Downloader\__init__.py", line 175, in start_helper
    self.start_once()
  File "E:\DanmakuRender-4\DMR\Downloader\__init__.py", line 142, in start_once
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Program Files\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\DanmakuRender-4\DMR\Downloader\__init__.py", line 130, in video_thread
    self.downloader.start()
  File "E:\DanmakuRender-4\DMR\Downloader\ffmpegio.py", line 213, in start
    return self.start_helper()
           ^^^^^^^^^^^^^^^^^^^
  File "E:\DanmakuRender-4\DMR\Downloader\ffmpegio.py", line 164, in start_helper
    raise RuntimeError(f'{self.taskname} 管道读取错误, 即将重试.')
RuntimeError: 小薛 管道读取错误, 即将重试.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DanmakuRender-4\DMR\Downloader\__init__.py", line 210, in stop_once
    self.downloader.stop()
  File "E:\DanmakuRender-4\DMR\Downloader\ffmpegio.py", line 241, in stop
    self.callback(self.thisfile)
  File "E:\DanmakuRender-4\DMR\Downloader\__init__.py", line 52, in segment_callback
    if self.segment_info is None or not exists(filename):
                                        ^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
[2023-06-02 22:31:54,032][__init__][DEBUG]: PIPE MESSAGE: {'src': 'downloader', 'msg': 'restart', 'type': 'error', 'group': '小薛', 'desc': RuntimeError('小薛 管道读取错误, 即将重试.')}
[2023-06-02 22:31:54,032][__init__][ERROR]: 录制 小薛 遇到错误，即将重试.
[2023-06-02 22:31:54,033][__init__][ERROR]: 小薛 管道读取错误, 即将重试.
[2023-06-02 22:31:54,033][connectionpool][DEBUG]: Starting new HTTPS connection (1): live.douyin.com:443
[2023-06-02 22:31:54,421][connectionpool][DEBUG]: https://live.douyin.com:443 "GET /42980448934 HTTP/1.1" 200 None
[2023-06-02 22:31:54,646][__init__][DEBUG]: PIPE MESSAGE: {'src': 'downloader', 'msg': 'start', 'type': 'info', 'group': '小薛'}
[2023-06-02 22:31:54,646][__init__][INFO]: 小薛 录制开始.
[2023-06-02 22:31:54,647][connectionpool][DEBUG]: Starting new HTTPS connection (1): live.douyin.com:443
[2023-06-02 22:31:54,965][connectionpool][DEBUG]: https://live.douyin.com:443 "GET /42980448934 HTTP/1.1" 200 None
[2023-06-02 22:31:55,303][connectionpool][DEBUG]: Starting new HTTPS connection (1): live.douyin.com:443
[2023-06-02 22:31:55,668][connectionpool][DEBUG]: https://live.douyin.com:443 "GET /42980448934 HTTP/1.1" 200 None
[2023-06-02 22:32:02,921][connectionpool][DEBUG]: Starting new HTTPS connection (1): live.douyin.com:443
[2023-06-02 22:32:03,557][connectionpool][DEBUG]: https://live.douyin.com:443 "GET /93912444706 HTTP/1.1" 200 None
[2023-06-02 22:32:04,192][connectionpool][DEBUG]: Starting new HTTPS connection (1): live.douyin.com:443
[2023-06-02 22:32:05,116][connectionpool][DEBUG]: https://live.douyin.com:443 "GET /972724142260 HTTP/1.1" 200 None

**Comment by SmallPeaches** [comment]
录制其他直播间正常吗？

**Comment by justdoiting** [comment]
> 录制其他直播间正常吗？

录了四五个都是正常的，就这个不行，应该是个别例

**Comment by SmallPeaches** [comment]
那他一般什么时候直播，我到时候去检查一下

**Comment by justdoiting** [comment]
> 那他一般什么时候直播，我到时候去检查一下

这两天都是晚上11点左右播

**Comment by SmallPeaches** [comment]
晚上我可能没时间看，你试下用streamgears引擎下载看看？

**Comment by justdoiting** [comment]
> 晚上我可能没时间看，你试下用streamgears引擎下载看看？

等她下次播我试试

**Comment by justdoiting** [comment]
> 晚上我可能没时间看，你试下用streamgears引擎下载看看？

用streamgears可以录，但是很容易就分段，看录好的视频是突然断掉的，网络是没有问题的
[DMR-20230606 - 副本.log](https://github.com/SmallPeaches/DanmakuRender/files/11666884/DMR-20230606.-.log)

**Comment by SmallPeaches** [comment]
感觉像是抖音的某种反爬机制？这里显示直播流已经结束了
你可以尝试一下用debug模式+ffmpeg下载器打开程序，看看会输出什么。
然后试试浏览器打开日志文件里面的流（以`http://pull-flv-l11.douyincdn.com`开头的那个链接），下载一段时间看看？

**Comment by justdoiting** [comment]
> 感觉像是抖音的某种反爬机制？这里显示直播流已经结束了 你可以尝试一下用debug模式+ffmpeg下载器打开程序，看看会输出什么。 然后试试浏览器打开日志文件里面的流（以`http://pull-flv-l11.douyincdn.com`开头的那个链接），下载一段时间看看？

我不会debug啊

**Comment by SmallPeaches** [comment]
就在启动的时候用`python main.py --debug` 命令启动，看看控制台会输出什么

**Comment by justdoiting** [comment]
> 就在启动的时候用`python main.py --debug` 命令启动，看看控制台会输出什么

这是我挂机用debug模式得到的日志，有一个视频还是损坏的
[DMR-20230608.log](https://github.com/SmallPeaches/DanmakuRender/files/11703719/DMR-20230608.log)

**Comment by SmallPeaches** [comment]
感觉这个问题比较麻烦，我有空了挂机找一下问题吧
