### ISSUE TITLE
第一次运行报错

### ISSUE THREAD

**Issue by yunbaitech-weiweixiaokeai-ml** [SmallPeaches/DanmakuRender#68]
机器: 家里电脑开的虚拟机 ubuntu22.04系统,  x86_64架构
```bash
oot@bilibili:~/hdusb/danmu/DanmakuRender# python3 main.py  --debug
/root/hdusb/danmu/DanmakuRender/tools/check_env.py:36: UserWarning: 程序正运行在Python 3.10及以上版本, 此版本有可能导致斗鱼弹幕录制错误, 如果出现此情况可以切换到Python 3.9版本.
  warnings.warn('程序正运行在Python 3.10及以上版本, 此版本有可能导致斗鱼弹幕录制错误, 如果出现此情况可以切换到Python 3.9版本.')
[2023-06-08 08:19:20,497][INFO]: 添加直播：https://www.huya.com/lpl
Traceback (most recent call last):
  File "/root/hdusb/danmu/DanmakuRender/main.py", line 85, in <module>
    dmr.start()
  File "/root/hdusb/danmu/DanmakuRender/DMR/__init__.py", line 42, in start
    downloader = Downloader(taskname=taskname, pipe=self.signal_queue, debug=self.debug, **replay_conf)
  File "/root/hdusb/danmu/DanmakuRender/DMR/Downloader/__init__.py", line 31, in __init__
    self.output_name = join(output_dir, output_name+f'.{vid_format}')
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by SmallPeaches** [comment]
配置文件没写好吧？输出文件夹是None了

**Comment by yunbaitech-weiweixiaokeai-ml** [comment]
配置文件,就改了个链接
![image](https://github.com/SmallPeaches/DanmakuRender/assets/127188624/4a5dca8f-f460-4b8b-ac9a-2550f07f490c)

**Comment by yunbaitech-weiweixiaokeai-ml** [comment]
改用toml配置文件吧, yaml一个空格错了看不出来呀

**Comment by yunbaitech-weiweixiaokeai-ml** [comment]
@SmallPeaches 
大佬你看看,我配置的自动上传部分,为啥会提示文件已经存在
```bash
root@bilibili:~/hdusb/danmu/DanmakuRender# python3 main.py 
/root/hdusb/danmu/DanmakuRender/tools/check_env.py:36: UserWarning: 程序正运行在Python 3.10及以上版本, 此版本有可能导致斗鱼弹幕录制错误, 如果出现此情况可以切换到Python 3.9版本.
  warnings.warn('程序正运行在Python 3.10及以上版本, 此版本有可能导致斗鱼弹幕录制错误, 如果出现此情况可以切换到Python 3.9版本.')
Traceback (most recent call last):
  File "/root/hdusb/danmu/DanmakuRender/main.py", line 85, in <module>
    dmr.start()
  File "/root/hdusb/danmu/DanmakuRender/DMR/__init__.py", line 31, in start
    uploader = Uploader(name,self.signal_queue,uploader_conf,debug=True)
  File "/root/hdusb/danmu/DanmakuRender/DMR/Uploader/__init__.py", line 19, in __init__
    self.uploader = getattr(pkg,uploader_config['engine'])(debug=self.debug, name=name, **uploader_config)
  File "/root/hdusb/danmu/DanmakuRender/DMR/Uploader/biliuprs.py", line 22, in __init__
    os.makedirs(os.path.dirname(self.cookies), exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/root/hdusb/biliup/biliup'
root@bilibili:~/hdusb/danmu/DanmakuRender# cat default.yml 
# FFprobe 可执行程序地址，为空自动搜索
ffprobe: ~
# FFmpeg 可执行程序地址，为空自动搜索
ffmpeg: ~
# biliup-rs可执行文件地址，为空自动搜索
biliup: /root/hdusb/biliup/biliup
...
...
```

**Comment by SmallPeaches** [comment]
你cookies那里填的啥？

**Comment by yunbaitech-weiweixiaokeai-ml** [comment]
@SmallPeaches 
![image](https://github.com/SmallPeaches/DanmakuRender/assets/127188624/df4c7161-12ad-4ef6-8931-3e134cbdc087)

我这台机器上部署biliup了, 是用的现成的

**Comment by SmallPeaches** [comment]
应该是这个文件名称和目录名称重复了，你有个文件叫`/root/hdusb/biliup/biliup`，cookies的目录也叫`/root/hdusb/biliup/biliup`，然后Python没法创建这个cookies文件了

**Comment by yunbaitech-weiweixiaokeai-ml** [comment]
@SmallPeaches 
我换成win10电脑可以了, 看样子我的电脑不行, 也没有cuda,太卡了. 录制的只有15帧,渲染之后直接一卡一卡的.
![image](https://github.com/SmallPeaches/DanmakuRender/assets/127188624/ddcd3072-886c-4bf9-9db0-55ccccc0db1d)

**Comment by SmallPeaches** [comment]
录制的话默认是原画，15fps是户外主播？
