### ISSUE TITLE
arm架构第一次运行报错

### ISSUE THREAD

**Issue by yunbaitech-weiweixiaokeai-ml** [SmallPeaches/DanmakuRender#69]
```bash
/home/ubuntu/workspace/danmu/DanmakuRender/tools/check_env.py:36: UserWarning: 程序正运行在Python 3.10及以上版本, 此版本有可能导致斗鱼弹幕录制错误, 如果出现此情况可以切换到Python 3.9版本.
  warnings.warn('程序正运行在Python 3.10及以上版本, 此版本有可能导致斗鱼弹幕录制错误, 如果出现此情况可以切换到Python 3.9版本.')
Traceback (most recent call last):
  File "/home/ubuntu/workspace/danmu/DanmakuRender/main.py", line 19, in <module>
    from DMR import DanmakuRender
  File "/home/ubuntu/workspace/danmu/DanmakuRender/DMR/__init__.py", line 8, in <module>
    from .Downloader import Downloader
  File "/home/ubuntu/workspace/danmu/DanmakuRender/DMR/Downloader/__init__.py", line 10, in <module>
    from DMR.Downloader.danmakuio import DanmakuWriter
  File "/home/ubuntu/workspace/danmu/DanmakuRender/DMR/Downloader/danmakuio.py", line 9, in <module>
    from DMR.LiveAPI.danmaku import DanmakuClient
  File "/home/ubuntu/workspace/danmu/DanmakuRender/DMR/LiveAPI/danmaku/__init__.py", line 10, in <module>
    from .douyin import Douyin
  File "/home/ubuntu/workspace/danmu/DanmakuRender/DMR/LiveAPI/danmaku/douyin/__init__.py", line 17, in <module>
    from .dy_pb2 import PushFrame, Response, ChatMessage
  File "/home/ubuntu/workspace/danmu/DanmakuRender/DMR/LiveAPI/danmaku/douyin/dy_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/usr/lib/python3/dist-packages/google/protobuf/internal/__init__.py)
```

**Comment by zxcec** [comment]
https://github.com/SmallPeaches/DanmakuRender/issues/66

可以参考我的问题，卸载再安装试试

**Comment by jth445600** [comment]
@zxcec 可以的，谢谢
