### ISSUE TITLE
第一次运行报错

### ISSUE THREAD

**Issue by Vae0514wzq** [SmallPeaches/DanmakuRender#74]
Traceback (most recent call last):
  File "F:\DanmakuRender-4\DMR\Downloader\__init__.py", line 175, in start_helper
    self.start_once()
  File "F:\DanmakuRender-4\DMR\Downloader\__init__.py", line 97, in start_once
    width, height = FFprobe.get_resolution(stream_url,stream_request_header)
  File "F:\DanmakuRender-4\DMR\utils.py", line 115, in get_resolution
    res = cls.run_ffprobe_livestream(url,header)
  File "F:\DanmakuRender-4\DMR\utils.py", line 95, in run_ffprobe_livestream
    out = subprocess.check_output([
  File "E:\Python\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "E:\Python\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\Python\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\Python\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
[2023-06-12 21:39:35,175][ERROR]: 录制 小风xF 遇到错误，即将重试.
[2023-06-12 21:39:35,176][ERROR]: [WinError 2] 系统找不到指定的文件。

**Comment by SmallPeaches** [comment]
ffprobe是不是没装好？可以考虑让程序自己安装

**Comment by Vae0514wzq** [comment]
用程序自己安装的解决问题了。还想问一下如果没设置分段，怎么结束录制带弹幕的视频？我看教程里面说不能直接关掉cmd窗口。只能等需要录制的直播结束吗

**Comment by Vae0514wzq** [comment]
![Snipaste_2023-06-13_13-50-47](https://github.com/SmallPeaches/DanmakuRender/assets/65432819/5753517a-f2b2-4447-b1f4-8eea8e62410a)
不需要这个黑色背景框是调整哪个参数，opacity吗？

**Comment by SmallPeaches** [comment]
ctrl+c就行

**Comment by Vae0514wzq** [comment]
如果程序正在录制中，此时需要添加一名主播进行录制，编辑了yml文件，保存之后只能断开当前的录制重启程序再进行录制吗

**Comment by SmallPeaches** [comment]
目前是这样，不过你还可以重新开一个终端启动

**Comment by Vae0514wzq** [comment]
![image](https://github.com/SmallPeaches/DanmakuRender/assets/65432819/266a5f7f-64b1-40cb-828f-bbf7327f6889)
这是啥问题？

**Comment by SmallPeaches** [comment]
这个应该是重试次数太多了，触发抖音的反爬策略了
