### ISSUE TITLE
最新代码录制错误

### ISSUE THREAD

**Issue by irelia97** [SmallPeaches/DanmakuRender#75]
之前用的是4月份左右的代码，除了自动上传功能有时出错，还能正常使用，就没更新
然后昨天pull了下代码发现用不了了，log如下
tips: 检查了下发现 795094feacbb4543ec5c9d53c5be47f92df4ab71 这个MR之前还是能正常用的

[2023-06-12 21:55:27,542][__init__][ERROR]: argument of type 'functools.partial' is not iterable
Traceback (most recent call last):
  File "D:\DanmakuRender-4\DMR\Downloader\__init__.py", line 175, in start_helper
    self.start_once()
  File "D:\DanmakuRender-4\DMR\Downloader\__init__.py", line 142, in start_once
    return future.result()
  File "C:\Users\Irelia\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\Irelia\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Irelia\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\DanmakuRender-4\DMR\Downloader\__init__.py", line 119, in video_thread
    self.downloader = self.download_class(
  File "D:\DanmakuRender-4\DMR\Downloader\ffmpegio.py", line 45, in __init__
    self.stream_type = 'flv' if '.flv' in self.stream_url else 'm3u8'
TypeError: argument of type 'functools.partial' is not iterable
[2023-06-12 21:55:27,599][danmakuio][DEBUG]: danmaku writer stoped.
[2023-06-12 21:55:27,599][__init__][ERROR]: 'NoneType' object has no attribute 'stop'
Traceback (most recent call last):
  File "D:\DanmakuRender-4\DMR\Downloader\__init__.py", line 175, in start_helper
    self.start_once()
  File "D:\DanmakuRender-4\DMR\Downloader\__init__.py", line 142, in start_once
    return future.result()
  File "C:\Users\Irelia\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\Irelia\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Irelia\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\DanmakuRender-4\DMR\Downloader\__init__.py", line 119, in video_thread
    self.downloader = self.download_class(
  File "D:\DanmakuRender-4\DMR\Downloader\ffmpegio.py", line 45, in __init__
    self.stream_type = 'flv' if '.flv' in self.stream_url else 'm3u8'
TypeError: argument of type 'functools.partial' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\DanmakuRender-4\DMR\Downloader\__init__.py", line 210, in stop_once
    self.downloader.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
[2023-06-12 21:55:27,599][__init__][DEBUG]: PIPE MESSAGE: {'src': 'downloader', 'msg': 'restart', 'type': 'error', 'group': '帝国时代肥龙大师', 'desc': TypeError("argument of type 'functools.partial' is not iterable")}

**Comment by SmallPeaches** [comment]
的确是bug，你可以暂时先用streamgears下载，等下次更新修复
