### ISSUE TITLE
录制到半夜无限重连

### ISSUE THREAD

**Issue by zxcec** [SmallPeaches/DanmakuRender#79]
1点前能下载和渲染，后面就出现问题

```
[2023-07-11 02:07:18,083][__init__][ERROR]: FFmpeg 异常退出.
Traceback (most recent call last):
  File "D:\desktop\kenni\DMR\Downloader\__init__.py", line 175, in start_helper
    self.start_once()
  File "D:\desktop\kenni\DMR\Downloader\__init__.py", line 142, in start_once
    return future.result()
  File "C:\Users\zzz71\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Users\zzz71\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Users\zzz71\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\desktop\kenni\DMR\Downloader\__init__.py", line 130, in video_thread
    self.downloader.start()
  File "D:\desktop\kenni\DMR\Downloader\ffmpegio.py", line 216, in start
    return self.start_helper()
  File "D:\desktop\kenni\DMR\Downloader\ffmpegio.py", line 161, in start_helper
    raise RuntimeError(f'FFmpeg 异常退出.')
RuntimeError: FFmpeg 异常退出.
[2023-07-11 02:07:18,091][danmakuio][DEBUG]: danmaku writer stoped.
[2023-07-11 02:07:18,092][ffmpegio][DEBUG]: 机智的肯尼 ffmpeg:    Last message repeated 1 times
[in#0/flv @ 000002546071c400] Error during demuxing: Error number -138 occurred
https://alirtspull.cc.netease.com/pushstation/9c61235a21b2591d1b97136224687.flv?src=web&quic_versions=46%2C43%2C39&auth_key=1688990330-40d90021f1184caea5a2febc4d56ad89-0-f7cb4146bef737ce5e3e650f39924a07: Error number -138 occurred
frame=1341843 fps= 60 q=-1.0 Lsize=N/A time=06:13:06.37 bitrate=N/A speed=0.999x    
video:14117782kB audio:437234kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

[2023-07-11 02:07:18,103][danmakuio][DEBUG]: New DMfile: ./直播回放\机智的肯尼-20230710-195350-Part007.ass
[2023-07-11 02:07:18,103][__init__][DEBUG]: PIPE MESSAGE: {'src': 'downloader', 'msg': './直播回放\\机智的肯尼-2023年07月11日01点53分.flv', 'type': 'split', 'group': '机智的肯尼', 'video_info': {'url': 'https://cc.163.com/239802416/', 'taskname': '机智的肯尼', 'streamer': '机智的肯尼', 'title': '', 'time': datetime.datetime(2023, 7, 11, 1, 53, 51, 739868), 'has_danmu': '', 'duration': 3600}}
[2023-07-11 02:07:18,103][__init__][INFO]: 分片 ./直播回放\机智的肯尼-2023年07月11日01点53分.flv 录制完成.
[2023-07-11 02:07:18,104][__init__][INFO]: 添加分片 ./直播回放\机智的肯尼-2023年07月11日01点53分.flv 至渲染队列.
[2023-07-11 02:07:18,105][connectionpool][DEBUG]: Starting new HTTPS connection (1): cc.163.com:443
[2023-07-11 02:07:18,192][danmakuio][DEBUG]: Cancel the future.
[2023-07-11 02:07:18,396][connectionpool][DEBUG]: https://cc.163.com:443 "GET /239802416/ HTTP/1.1" 200 None
[2023-07-11 02:07:18,426][ffmpegio][DEBUG]: ffmpeg downloader stoped.
[2023-07-11 02:07:18,426][__init__][DEBUG]: PIPE MESSAGE: {'src': 'downloader', 'msg': 'restart', 'type': 'error', 'group': '机智的肯尼', 'desc': RuntimeError('FFmpeg 异常退出.')}
[2023-07-11 02:07:18,426][__init__][ERROR]: 录制 机智的肯尼 遇到错误，即将重试.
[2023-07-11 02:07:18,427][__init__][ERROR]: FFmpeg 异常退出.
[2023-07-11 02:07:18,429][connectionpool][DEBUG]: Starting new HTTPS connection (1): cc.163.com:443
[2023-07-11 02:07:18,701][connectionpool][DEBUG]: https://cc.163.com:443 "GET /239802416/ HTTP/1.1" 200 None
[2023-07-11 02:07:18,732][__init__][DEBUG]: PIPE MESSAGE: {'src': 'downloader', 'msg': 'start', 'type': 'info', 'group': '机智的肯尼'}
[2023-07-11 02:07:18,733][__init__][INFO]: 机智的肯尼 录制开始.
[2023-07-11 02:07:18,734][connectionpool][DEBUG]: Starting new HTTPS connection (1): cc.163.com:443
[2023-07-11 02:07:19,015][connectionpool][DEBUG]: https://cc.163.com:443 "GET /239802416/ HTTP/1.1" 200 None
[2023-07-11 02:07:19,050][connectionpool][DEBUG]: Starting new HTTPS connection (1): vapi.cc.163.com:443
[2023-07-11 02:07:19,233][connectionpool][DEBUG]: https://vapi.cc.163.com:443 "GET /video_play_url/239802416?vbrmode=1&secure=1&vbrname=original&vbr= HTTP/1.1" 200 1170
[2023-07-11 02:07:49,648][connectionpool][DEBUG]: Starting new HTTPS connection (1): cc.163.com:443
[2023-07-11 02:07:49,945][connectionpool][DEBUG]: https://cc.163.com:443 "GET /239802416/ HTTP/1.1" 200 None
[2023-07-11 02:07:49,973][__init__][ERROR]: Command '['ffprobe', '-headers', 'Content-Type: application/x-www-form-urlencoded\r\nUser-Agent: Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Mobile Safari/537.36 \r\n', '-i', 'https://alirtspull.cc.netease.com/pushstation/9c61235a21b2591d1b97136224687.flv?src=web&quic_versions=46%2C43%2C39&auth_key=1689012739-6140e12b4da8415db74791ff74ed6e1b-0-e470d3b51954fe7d9128d86770d93220', '-select_streams', 'v:0', '-print_format', 'json', '-show_format', '-show_streams', '-v', 'quiet']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "D:\desktop\kenni\DMR\Downloader\__init__.py", line 175, in start_helper
    self.start_once()
  File "D:\desktop\kenni\DMR\Downloader\__init__.py", line 97, in start_once
    width, height = FFprobe.get_resolution(stream_url,stream_request_header)
  File "D:\desktop\kenni\DMR\utils.py", line 115, in get_resolution
    res = cls.run_ffprobe_livestream(url,header)
  File "D:\desktop\kenni\DMR\utils.py", line 95, in run_ffprobe_livestream
    out = subprocess.check_output([
  File "C:\Users\zzz71\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\zzz71\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffprobe', '-headers', 'Content-Type: application/x-www-form-urlencoded\r\nUser-Agent: Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Mobile Safari/537.36 \r\n', '-i', 'https://alirtspull.cc.netease.com/pushstation/9c61235a21b2591d1b97136224687.flv?src=web&quic_versions=46%2C43%2C39&auth_key=1689012739-6140e12b4da8415db74791ff74ed6e1b-0-e470d3b51954fe7d9128d86770d93220', '-select_streams', 'v:0', '-print_format', 'json', '-show_format', '-show_streams', '-v', 'quiet']' returned non-zero exit status 1.
```

完整文件  0710的3570行开始
[DMR-20230710.log](https://github.com/SmallPeaches/DanmakuRender/files/12010313/DMR-20230710.log)
[DMR-20230711.log](https://github.com/SmallPeaches/DanmakuRender/files/12010314/DMR-20230711.log)

**Comment by SmallPeaches** [comment]
感觉像是流失效了，然后返回错误，是不是这个主播在两点下播了？

**Comment by zxcec** [comment]
> 感觉像是流失效了，然后返回错误，是不是这个主播在两点下播了？

可能是网易cc半夜服务器有毛病，我把这个问题关了
