### ISSUE TITLE
安装好了后，启动不了

### ISSUE THREAD

**Issue by laotang8** [SmallPeaches/DanmakuRender#87]
安装好了后，启动不了，有没有交流群啊

**Comment by laotang8** [comment]
PS C:\Users\Administrator\Desktop\DanmakuRender-2023.6.15> python main.py
检查更新失败.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\DanmakuRender-2023.6.15\main.py", line 53, in <module>
    default_config = yaml.safe_load(f)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "default.yml", line 2, column 1
expected <block end>, but found '<block mapping start>'
  in "default.yml", line 14, column 3
PS C:\Users\Administrator\Desktop\DanmakuRender-2023.6.15>




以上是错误提示

**Comment by SmallPeaches** [comment]
应该是你配置文件格式不对导致的，你注意一下空格，或者是直接默认先试一下？
